In [1]:
import numpy as np

#### Numpy

The NumPy library is the core library for scientific computing in Python.
It provides a high-performance multidimensional arrayobject, and tools for working with arrays.

In [22]:
# Creating Arrays
a = np.array([1,2,3])
print(a.shape)
b = np.array([[1,2,3], [4,5,6]], dtype=float)
print(b.shape)
c = np.array([[1.5,2,3], [4,5,6], [7,8,9]], dtype=float)
print(c.shape)

(3,)
(2, 3)
(3, 3)


#### Initial Placeholders

In [39]:
# (rows, cols)
np.zeros((2,3,4), dtype=int) # Create an array of zeros

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [38]:
np.ones((2,3,4), dtype=np.int16) # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
np.arange(1,10,2) # Create an array of evenly spaced values (step value)

array([1, 3, 5, 7, 9])

In [34]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [36]:
np.full((3,4), 1) # Create a constant array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
np.eye(5) # Create a 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.random.random((2,3)) # Create an array with random value

array([[0.44030019, 0.30000767, 0.25326002],
       [0.65116517, 0.69909062, 0.27500625]])

In [48]:
np.empty((3,2)) # Create an empty array

array([[0.44030019, 0.30000767],
       [0.25326002, 0.65116517],
       [0.69909062, 0.27500625]])

#### I/O

In [50]:
# Saving and Loading on Disk
a = np.array([1,2,3])
np.save('my_array', a)

In [51]:
# Loading 
np.load('my_array.npy')

array([1, 2, 3])

In [62]:
# Saving and Loading Text Files
np.loadtxt('myfile.txt', dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.savetxt('myarray.txt', a, delimiter=" ")

In [64]:
# Asking for help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


#### Inspecting Array