In [1]:
import numpy as np

#### Numpy

The NumPy library is the core library for scientific computing in Python.
It provides a high-performance multidimensional arrayobject, and tools for working with arrays.

In [22]:
# Creating Arrays
a = np.array([1,2,3])
print(a.shape)
b = np.array([[1,2,3], [4,5,6]], dtype=float)
print(b.shape)
c = np.array([[1.5,2,3], [4,5,6], [7,8,9]], dtype=float)
print(c.shape)

(3,)
(2, 3)
(3, 3)


#### Initial Placeholders

In [39]:
# (rows, cols)
np.zeros((2,3,4), dtype=int) # Create an array of zeros

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [38]:
np.ones((2,3,4), dtype=np.int16) # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
np.arange(1,10,2) # Create an array of evenly spaced values (step value)

array([1, 3, 5, 7, 9])

In [34]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [36]:
np.full((3,4), 1) # Create a constant array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
np.eye(5) # Create a 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.random.random((2,3)) # Create an array with random value

array([[0.44030019, 0.30000767, 0.25326002],
       [0.65116517, 0.69909062, 0.27500625]])

In [48]:
np.empty((3,2)) # Create an empty array

array([[0.44030019, 0.30000767],
       [0.25326002, 0.65116517],
       [0.69909062, 0.27500625]])

#### I/O

In [50]:
# Saving and Loading on Disk
a = np.array([1,2,3])
np.save('my_array', a)

In [51]:
# Loading 
np.load('my_array.npy')

array([1, 2, 3])

In [62]:
# Saving and Loading Text Files
np.loadtxt('myfile.txt', dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.savetxt('myarray.txt', a, delimiter=" ")

In [64]:
# Asking for help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


#### Inspecting Array

In [77]:
a = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(a.shape) # Array dimensions
print(len(a)) # Length of Array
print(a.ndim) # Number of array dimensions
print(a.size) # Number of Array elements
print(a.dtype) # Data type of array elements
print(a.dtype.name) # Name of data type
print(a.astype('float')) # Convert an array to a different type

(2, 5)
2
2
10
int32
int32
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


#### Data Types

In [82]:
np.int64, np.float32, np.complex, np.bool, np.object, np.string_, np.unicode_

(numpy.int64, numpy.float32, complex, bool, object, numpy.bytes_, numpy.str_)

#### Array Mathematics

In [87]:
a = np.array([(1,2,3,4,5), (6,7,8,9,10)])
b = np.array([(-1,5,4,6,10), (-9,-5,1,8,12)])
a-b

array([[ 2, -3, -1, -2, -5],
       [15, 12,  7,  1, -2]])

In [88]:
np.subtract(a,b)

array([[ 2, -3, -1, -2, -5],
       [15, 12,  7,  1, -2]])

In [89]:
# Addition
a+b

array([[ 0,  7,  7, 10, 15],
       [-3,  2,  9, 17, 22]])

In [90]:
np.add(a,b)

array([[ 0,  7,  7, 10, 15],
       [-3,  2,  9, 17, 22]])

In [93]:
# Division
a/b

array([[-1.        ,  0.4       ,  0.75      ,  0.66666667,  0.5       ],
       [-0.66666667, -1.4       ,  8.        ,  1.125     ,  0.83333333]])

In [94]:
np.divide(a,b)

array([[-1.        ,  0.4       ,  0.75      ,  0.66666667,  0.5       ],
       [-0.66666667, -1.4       ,  8.        ,  1.125     ,  0.83333333]])

In [95]:
# Multiplication
a*b

array([[ -1,  10,  12,  24,  50],
       [-54, -35,   8,  72, 120]])

In [96]:
np.multiply(a,b)

array([[ -1,  10,  12,  24,  50],
       [-54, -35,   8,  72, 120]])

In [99]:
np.exp(a) # Exponentiation

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [102]:
np.sqrt(a) # Square root        

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [103]:
np.sin(a) # Print sines of an array

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [104]:
np.cos(b) # Element wise cosine

array([[ 0.54030231,  0.28366219, -0.65364362,  0.96017029, -0.83907153],
       [-0.91113026,  0.28366219,  0.54030231, -0.14550003,  0.84385396]])

In [105]:
np.log(a) # Element wise natural logarithm

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [110]:
x = np.array([1,2])
y = np.array([3])

#### Comparisons 

In [112]:
a == b # Element wise comparison

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [114]:
b < 2 # Element wise comparison

array([[ True, False, False, False, False],
       [ True,  True,  True, False, False]])

In [115]:
np.array_equal(a,b) # Array wise comparison

False

#### Aggregate Functions

In [116]:
a.sum() # Array-wise sum 

55

In [117]:
a.min() # Minimum value

1

In [118]:
a.max() # Maximum value

10

In [125]:
b

array([[-1,  5,  4,  6, 10],
       [-9, -5,  1,  8, 12]])

In [127]:
b.max(axis=1) # Takes the maximum for each rows

array([10, 12])

In [128]:
b.max(axis=0) # Takes the maximum row

array([-1,  5,  4,  8, 12])

In [130]:
b.cumsum(axis=1) # Take cum sum of each row

array([[ -1,   4,   8,  14,  24],
       [ -9, -14, -13,  -5,   7]], dtype=int32)

In [131]:
b.cumsum(axis=0)

array([[ -1,   5,   4,   6,  10],
       [-10,   0,   5,  14,  22]], dtype=int32)

In [132]:
a.mean() # Mean

5.5

In [134]:
np.median(a) # Median

5.5

In [135]:
np.corrcoef(a) # Correlation coefficent

array([[1., 1.],
       [1., 1.]])

In [136]:
np.std(a) # Standard deviation

2.8722813232690143